In [2]:
import pandas as pd

constituents_url = 'https://raw.githubusercontent.com/NationalGalleryOfArt/opendata/08bc72ca5fccf86ca4f3702f9db068a11a592509/data/constituents.csv'
cons_df = pd.read_csv(constituents_url)
objects_url = 'https://raw.githubusercontent.com/NationalGalleryOfArt/opendata/refs/heads/main/data/objects.csv'
objects_df = pd.read_csv(objects_url)
objects_constituents_url = 'https://raw.githubusercontent.com/NationalGalleryOfArt/opendata/refs/heads/main/data/objects_constituents.csv'
objects_cons_df = pd.read_csv(objects_constituents_url)
text_entries_url = 'https://raw.githubusercontent.com/NationalGalleryOfArt/opendata/refs/heads/main/data/objects_text_entries.csv'
text_entries_df = pd.read_csv(text_entries_url)
media_items_url = 'https://raw.githubusercontent.com/NationalGalleryOfArt/opendata/refs/heads/main/data/media_items.csv'
media_df = pd.read_csv(media_items_url)
media_relationships_url = 'https://raw.githubusercontent.com/NationalGalleryOfArt/opendata/refs/heads/main/data/media_relationships.csv'
media_relationships_df = pd.read_csv(media_relationships_url)

/var/folders/vt/5lpj5r5j0sg4g69qhz9_kqzc0000gn/T/ipykernel_27995/689904132.py:6: DtypeWarning: Columns (24) have mixed types. Specify dtype option on import or set low_memory=False.
  objects_df = pd.read_csv(objects_url)
/var/folders/vt/5lpj5r5j0sg4g69qhz9_kqzc0000gn/T/ipykernel_27995/689904132.py:8: DtypeWarning: Columns (11) have mixed types. Specify dtype option on import or set low_memory=False.
  objects_cons_df = pd.read_csv(objects_constituents_url)

## Data Cleaning

In [3]:
media_relationships_df.dtypes
media_relationships_df.isna().sum()

mediaid          0
relatedid        0
relatedentity    0
dtype: int64

In [4]:
media_df.isna().sum()
media_df.dtypes

mediaid               int64
mediatype            object
title                object
description          object
duration            float64
language             object
thumbnailurl         object
playurl              object
downloadurl          object
keywords             object
tags                 object
imageurl             object
presentationdate     object
releasedate          object
lastmodified         object
dtype: object

In [5]:
objects_df.isna().sum()

objectid                            0
uuid                                0
accessioned                         0
accessionnum                        0
locationid                     141720
title                               0
displaydate                     11524
beginyear                          50
endyear                            68
visualbrowsertimespan              50
medium                           1241
dimensions                      21017
inscription                     60826
markings                       129078
attributioninverted                 0
attribution                         0
provenancetext                  64958
creditline                         25
classification                      0
subclassification              101617
visualbrowserclassification         0
parentid                       114107
isvirtual                           0
departmentabbr                      0
portfolio                      141379
series                         105364
volume                         141818
watermarks                     134252
lastdetectedmodification            0
wikidataid                      16580
customprinturl                 143701
dtype: int64

In [6]:
limit = len(objects_df) * 0.7
objects_df = objects_df.dropna(thresh=limit, axis=1)

In [7]:
target_cols = ['medium', 'dimensions', 'inscription', 'markings', 'provenancetext']

available_cols = [col for col in target_cols if col in objects_df.columns]

objects_df[available_cols] = objects_df[available_cols].fillna("Unknown")

In [8]:
print(objects_df.columns.tolist())

['objectid', 'uuid', 'accessioned', 'accessionnum', 'title', 'displaydate', 'beginyear', 'endyear', 'visualbrowsertimespan', 'medium', 'dimensions', 'attributioninverted', 'attribution', 'creditline', 'classification', 'visualbrowserclassification', 'isvirtual', 'departmentabbr', 'lastdetectedmodification', 'wikidataid']

In [9]:
objects_df = objects_df.dropna(subset=['beginyear', 'endyear', 'creditline', 'visualbrowsertimespan'])

In [10]:
objects_df.isna().sum()

objectid                           0
uuid                               0
accessioned                        0
accessionnum                       0
title                              0
displaydate                    11472
beginyear                          0
endyear                            0
visualbrowsertimespan              0
medium                             0
dimensions                         0
attributioninverted                0
attribution                        0
creditline                         0
classification                     0
visualbrowserclassification        0
isvirtual                          0
departmentabbr                     0
lastdetectedmodification           0
wikidataid                     16512
dtype: int64

In [11]:
if 'displaydate' in objects_df.columns:
    objects_df['displaydate'] = objects_df['displaydate'].fillna(objects_df['beginyear'].astype(str))
    
if 'wikidataid' in objects_df.columns:
    objects_df['wikidataid'] = objects_df['wikidataid'].fillna('Not Linked')

In [12]:
objects_df.isna().sum()

objectid                       0
uuid                           0
accessioned                    0
accessionnum                   0
title                          0
displaydate                    0
beginyear                      0
endyear                        0
visualbrowsertimespan          0
medium                         0
dimensions                     0
attributioninverted            0
attribution                    0
creditline                     0
classification                 0
visualbrowserclassification    0
isvirtual                      0
departmentabbr                 0
lastdetectedmodification       0
wikidataid                     0
dtype: int64

In [23]:
objects_cons_df.dtypes
objects_cons_df.isna().sum()
#objects_cons_df.roletype.unique()
#objects_cons_df
objects_cons_df['objectid'] = objects_cons_df['objectid'].replace(0, 'NaN')

In [14]:
objects_df.isna().sum()

objectid                       0
uuid                           0
accessioned                    0
accessionnum                   0
title                          0
displaydate                    0
beginyear                      0
endyear                        0
visualbrowsertimespan          0
medium                         0
dimensions                     0
attributioninverted            0
attribution                    0
creditline                     0
classification                 0
visualbrowserclassification    0
isvirtual                      0
departmentabbr                 0
lastdetectedmodification       0
wikidataid                     0
dtype: int64

Constituents, objects_constituents down

In [24]:
objects_cons_df.dtypes
objects_cons_df.isna().sum()
objects_cons_df

,objectid,constituentid,displayorder,roletype,role,prefix,suffix,displaydate,beginyear,endyear,country,zipcode
0,NaN,12,4,owner,current owner,NaN,NaN,1937 -,1937.0,NaN,United States,20565.0
1,NaN,427,1,donor,donor,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,427,2,donor,source,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,427,3,owner,previous owner,NaN,NaN,1936 - 1937,1936.0,1937.0,NaN,NaN
4,NaN,1102,1,owner,previous owner,NaN,", New York, NY",- 1936,NaN,1936.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
839057,233967,12,2,owner,current owner,NaN,NaN,NaN,NaN,NaN,NaN,NaN
839058,233967,27654,1,donor,source,NaN,NaN,NaN,NaN,NaN,NaN,NaN
839059,233967,27654,1,owner,previous owner,NaN,NaN,NaN,NaN,NaN,NaN,NaN
839060,233967,27654,2,donor,donor,NaN,NaN,NaN,NaN,NaN,NaN,NaN
839061,233967,44363,1,artist,artist,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
cons_df.dtypes
cons_df.isna().sum()
cons_df
remove = ['anonymous artist', 'anonymous']
cons_df['preferreddisplayname'] = cons_df['preferreddisplayname'].str.lower().str.strip()
cons_df['preferreddisplayname'] = cons_df['preferreddisplayname'].replace(remove, 'Anonymous')
cons_df
cons_df['forwarddisplayname'] = cons_df['forwarddisplayname'].str.lower().str.strip()
cons_df['forwarddisplayname'] = cons_df['forwarddisplayname'].replace(remove, 'Anonymous')
cons_df

,constituentid,uuid,ulanid,preferreddisplayname,forwarddisplayname,lastname,displaydate,artistofngaobject,beginyear,endyear,visualbrowsertimespan,nationality,visualbrowsernationality,constituenttype,wikidataid
0,9,57edbe2d-6702-4d41-9190-2a2945bc2c89,NaN,Anonymous,Anonymous,NaN,Anonymous,0,NaN,NaN,NaN,NaN,Other,anonymous,NaN
1,11,125c640d-e39b-4ae4-8455-f0b5e913c09e,NaN,"baldung, hans",hans baldung,Baldung,NaN,1,NaN,NaN,NaN,NaN,Other,individual,NaN
2,12,e4d45117-9800-4315-9184-916c53e64c8d,500115983.0,national gallery of art,national gallery of art,NaN,NaN,0,NaN,NaN,NaN,NaN,Other,corporate,Q214867
3,13,7331a3f2-50fd-4838-b41d-f8013eb2456c,NaN,Anonymous,Anonymous,Anonymous Artist,NaN,1,NaN,NaN,NaN,Unknown,Other,anonymous,Q4233718
4,14,6b4e3681-b09e-4cbd-9f3c-ff7830173c59,NaN,"evans, thomas m., mrs.",mrs. thomas m. evans,Evans,"American, 1923 - 2013",0,1923.0,2013.0,1901 to 1925,American,American,individual,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27766,54663,7e507508-19be-46a5-ac77-dceb689fc6b4,NaN,alex cooper auctioneers,alex cooper auctioneers,NaN,founded 1924,0,1924.0,NaN,1901 to 1925,NaN,Other,corporate,NaN
27767,54692,cc016903-caeb-473c-821a-b27d5b254b8b,NaN,"prager, joanne",joanne prager,Prager,NaN,0,NaN,NaN,NaN,NaN,Other,individual,NaN
27768,54706,126a49b4-5184-4a31-864f-ae62f425b5c6,NaN,craven allen gallery,craven allen gallery,NaN,NaN,0,NaN,NaN,NaN,NaN,Other,corporate,NaN
27769,54719,70c9d72b-9e65-4796-8090-4eb59da84357,NaN,"bullock, raymond",raymond bullock,Bullock,American,0,NaN,NaN,NaN,American,American,individual,NaN
27770,54759,42d329a1-81c5-427e-84ff-21bafca600a9,NaN,"odieuvre, michel",michel odieuvre,Odieuvre,"French, 1687 - 1756",1,1687.0,1756.0,1651 to 1700,French,French,individual,NaN

## Creating Database

In [1]:
import duckdb
import pandas as pd
import os

con = duckdb.connect("Museum.db")
print("Connected to Museum.db")

Connected to Museum.db