In [1]:
import pandas as pd

constituents_url = 'https://raw.githubusercontent.com/NationalGalleryOfArt/opendata/08bc72ca5fccf86ca4f3702f9db068a11a592509/data/constituents.csv'
cons_df = pd.read_csv(constituents_url)
objects_url = 'https://raw.githubusercontent.com/NationalGalleryOfArt/opendata/refs/heads/main/data/objects.csv'
objects_df = pd.read_csv(objects_url)
objects_constituents_url = 'https://raw.githubusercontent.com/NationalGalleryOfArt/opendata/refs/heads/main/data/objects_constituents.csv'
objects_cons_df = pd.read_csv(objects_constituents_url)
text_entries_url = 'https://raw.githubusercontent.com/NationalGalleryOfArt/opendata/refs/heads/main/data/objects_text_entries.csv'
text_entries_df = pd.read_csv(text_entries_url)
media_items_url = 'https://raw.githubusercontent.com/NationalGalleryOfArt/opendata/refs/heads/main/data/media_items.csv'
media_df = pd.read_csv(media_items_url)
media_relationships_url = 'https://raw.githubusercontent.com/NationalGalleryOfArt/opendata/refs/heads/main/data/media_relationships.csv'
media_relationships_df = pd.read_csv(media_relationships_url)

/var/folders/w7/23_x_krd56dgz3l_g0tp_m0w0000gn/T/ipykernel_81631/689904132.py:6: DtypeWarning: Columns (24) have mixed types. Specify dtype option on import or set low_memory=False.
  objects_df = pd.read_csv(objects_url)
/var/folders/w7/23_x_krd56dgz3l_g0tp_m0w0000gn/T/ipykernel_81631/689904132.py:8: DtypeWarning: Columns (11) have mixed types. Specify dtype option on import or set low_memory=False.
  objects_cons_df = pd.read_csv(objects_constituents_url)

## Data Cleaning

In [2]:
media_relationships_df.dtypes
media_relationships_df.isna().sum()

mediaid          0
relatedid        0
relatedentity    0
dtype: int64

In [3]:
media_df.isna().sum()
media_df.dtypes

mediaid               int64
mediatype            object
title                object
description          object
duration            float64
language             object
thumbnailurl         object
playurl              object
downloadurl          object
keywords             object
tags                 object
imageurl             object
presentationdate     object
releasedate          object
lastmodified         object
dtype: object

In [4]:
objects_df.isna().sum()

objectid                            0
uuid                                0
accessioned                         0
accessionnum                        0
locationid                     142958
title                               0
displaydate                     11515
beginyear                          66
endyear                            84
visualbrowsertimespan              66
medium                           1241
dimensions                      20946
inscription                     60972
markings                       130507
attributioninverted                 0
attribution                         0
provenancetext                  64673
creditline                         25
classification                      0
subclassification              103104
visualbrowserclassification         0
parentid                       115539
isvirtual                           0
departmentabbr                      0
portfolio                      141573
series                         106754
volume                         143281
watermarks                     135677
lastdetectedmodification            0
wikidataid                      18041
customprinturl                 145164
dtype: int64

In [5]:
limit = len(objects_df) * 0.7
objects_df = objects_df.dropna(thresh=limit, axis=1)

In [6]:
target_cols = ['medium', 'dimensions', 'inscription', 'markings', 'provenancetext']

available_cols = [col for col in target_cols if col in objects_df.columns]

objects_df[available_cols] = objects_df[available_cols].fillna("Unknown")

In [7]:
print(objects_df.columns.tolist())

['objectid', 'uuid', 'accessioned', 'accessionnum', 'title', 'displaydate', 'beginyear', 'endyear', 'visualbrowsertimespan', 'medium', 'dimensions', 'attributioninverted', 'attribution', 'creditline', 'classification', 'visualbrowserclassification', 'isvirtual', 'departmentabbr', 'lastdetectedmodification', 'wikidataid']

In [8]:
objects_df = objects_df.dropna(subset=['beginyear', 'endyear', 'creditline', 'visualbrowsertimespan'])

In [9]:
objects_df.isna().sum()

objectid                           0
uuid                               0
accessioned                        0
accessionnum                       0
title                              0
displaydate                    11463
beginyear                          0
endyear                            0
visualbrowsertimespan              0
medium                             0
dimensions                         0
attributioninverted                0
attribution                        0
creditline                         0
classification                     0
visualbrowserclassification        0
isvirtual                          0
departmentabbr                     0
lastdetectedmodification           0
wikidataid                     17958
dtype: int64

In [10]:
if 'displaydate' in objects_df.columns:
    objects_df['displaydate'] = objects_df['displaydate'].fillna(objects_df['beginyear'].astype(str))
    
if 'wikidataid' in objects_df.columns:
    objects_df['wikidataid'] = objects_df['wikidataid'].fillna('Not Linked')

In [11]:
objects_df.isna().sum()

objectid                       0
uuid                           0
accessioned                    0
accessionnum                   0
title                          0
displaydate                    0
beginyear                      0
endyear                        0
visualbrowsertimespan          0
medium                         0
dimensions                     0
attributioninverted            0
attribution                    0
creditline                     0
classification                 0
visualbrowserclassification    0
isvirtual                      0
departmentabbr                 0
lastdetectedmodification       0
wikidataid                     0
dtype: int64

In [12]:
objects_cons_df.dtypes
objects_cons_df.isna().sum()
#objects_cons_df.roletype.unique()
#objects_cons_df
objects_cons_df['objectid'] = objects_cons_df['objectid'].replace(0, 'NaN')

In [13]:
objects_df.isna().sum()

objectid                       0
uuid                           0
accessioned                    0
accessionnum                   0
title                          0
displaydate                    0
beginyear                      0
endyear                        0
visualbrowsertimespan          0
medium                         0
dimensions                     0
attributioninverted            0
attribution                    0
creditline                     0
classification                 0
visualbrowserclassification    0
isvirtual                      0
departmentabbr                 0
lastdetectedmodification       0
wikidataid                     0
dtype: int64

Constituents, objects_constituents down

In [14]:
objects_cons_df.dtypes
objects_cons_df.isna().sum()
objects_cons_df

,objectid,constituentid,displayorder,roletype,role,prefix,suffix,displaydate,beginyear,endyear,country,zipcode
0,NaN,12,4,owner,current owner,NaN,NaN,1937 -,1937.0,NaN,United States,20565.0
1,NaN,427,1,donor,donor,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,427,2,donor,source,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,427,3,owner,previous owner,NaN,NaN,1936 - 1937,1936.0,1937.0,NaN,NaN
4,NaN,1102,1,owner,previous owner,NaN,", New York, NY",- 1936,NaN,1936.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
846432,234295,12,2,owner,current owner,NaN,NaN,NaN,NaN,NaN,NaN,NaN
846433,234295,35183,2,donor,donor,NaN,NaN,NaN,NaN,NaN,NaN,NaN
846434,234295,45804,1,artist,artist,NaN,NaN,NaN,NaN,NaN,NaN,NaN
846435,234295,45804,1,donor,source,NaN,NaN,NaN,NaN,NaN,NaN,NaN
846436,234295,45804,1,owner,previous owner,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
cons_df.dtypes
cons_df.isna().sum()
cons_df
remove = ['anonymous artist', 'anonymous']
cons_df['preferreddisplayname'] = cons_df['preferreddisplayname'].str.lower().str.strip()
cons_df['preferreddisplayname'] = cons_df['preferreddisplayname'].replace(remove, 'Anonymous')
cons_df
cons_df['forwarddisplayname'] = cons_df['forwarddisplayname'].str.lower().str.strip()
cons_df['forwarddisplayname'] = cons_df['forwarddisplayname'].replace(remove, 'Anonymous')
cons_df

,constituentid,uuid,ulanid,preferreddisplayname,forwarddisplayname,lastname,displaydate,artistofngaobject,beginyear,endyear,visualbrowsertimespan,nationality,visualbrowsernationality,constituenttype,wikidataid
0,9,57edbe2d-6702-4d41-9190-2a2945bc2c89,NaN,Anonymous,Anonymous,NaN,Anonymous,0,NaN,NaN,NaN,NaN,Other,anonymous,NaN
1,11,125c640d-e39b-4ae4-8455-f0b5e913c09e,NaN,"baldung, hans",hans baldung,Baldung,NaN,1,NaN,NaN,NaN,NaN,Other,individual,NaN
2,12,e4d45117-9800-4315-9184-916c53e64c8d,500115983.0,national gallery of art,national gallery of art,NaN,NaN,0,NaN,NaN,NaN,NaN,Other,corporate,Q214867
3,13,7331a3f2-50fd-4838-b41d-f8013eb2456c,NaN,Anonymous,Anonymous,Anonymous Artist,NaN,1,NaN,NaN,NaN,Unknown,Other,anonymous,Q4233718
4,14,6b4e3681-b09e-4cbd-9f3c-ff7830173c59,NaN,"evans, thomas m., mrs.",mrs. thomas m. evans,Evans,"American, 1923 - 2013",0,1923.0,2013.0,1901 to 1925,American,American,individual,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27766,54663,7e507508-19be-46a5-ac77-dceb689fc6b4,NaN,alex cooper auctioneers,alex cooper auctioneers,NaN,founded 1924,0,1924.0,NaN,1901 to 1925,NaN,Other,corporate,NaN
27767,54692,cc016903-caeb-473c-821a-b27d5b254b8b,NaN,"prager, joanne",joanne prager,Prager,NaN,0,NaN,NaN,NaN,NaN,Other,individual,NaN
27768,54706,126a49b4-5184-4a31-864f-ae62f425b5c6,NaN,craven allen gallery,craven allen gallery,NaN,NaN,0,NaN,NaN,NaN,NaN,Other,corporate,NaN
27769,54719,70c9d72b-9e65-4796-8090-4eb59da84357,NaN,"bullock, raymond",raymond bullock,Bullock,American,0,NaN,NaN,NaN,American,American,individual,NaN
27770,54759,42d329a1-81c5-427e-84ff-21bafca600a9,NaN,"odieuvre, michel",michel odieuvre,Odieuvre,"French, 1687 - 1756",1,1687.0,1756.0,1651 to 1700,French,French,individual,NaN

## Creating Database

In [16]:
import duckdb
import pandas as pd
import os

con = duckdb.connect("Museum.db")
print("Connected to Museum.db")

Connected to Museum.db

In [17]:
print(objects_df.dtypes)

objectid                         int64
uuid                            object
accessioned                      int64
accessionnum                    object
title                           object
displaydate                     object
beginyear                      float64
endyear                        float64
visualbrowsertimespan           object
medium                          object
dimensions                      object
attributioninverted             object
attribution                     object
creditline                      object
classification                  object
visualbrowserclassification     object
isvirtual                        int64
departmentabbr                  object
lastdetectedmodification        object
wikidataid                      object
dtype: object

In [18]:
# with open("museum.sql", "w") as file:
#     file.write("""
#      CREATE OR REPLACE TABLE objects (
#         objectid INTEGER,
#         uuid TEXT,
#         accessioned INTEGER,
#         accessionnum TEXT,
#         title TEXT,
#         displaydate DATE,
#         beginyear FLOAT,
#         endyear FLOAT,
#         visualbrowsertimespan TEXT,
#         medium TEXT,
#         dimensions TEXT,
#         attributioninverted TEXT,
#         attribution TEXT,
#         creditline TEXT,
#         classification TEXT,
#         isvirtual INTEGER,
#         departmntabbr TEXT,
#         lastdetectmodification TEXT,
#         wikidataid TEXT,
#         merged_classification TEXT,
#         PRIMARY KEY (objectid)
#         );
               
#     CREATE OR REPLACE TABLE cons (
#         constituentid INTEGER,
#         uuid INTEGER,
#         ulanid FLOAT,
#         preferreddisplayname TEXT,
#         forwarddisplayname TEXT,
#         lastname TEXT,
#         displaydate TEXT,
#         artistofngaobject INT,
#         beginyear FLOAT,
#         endyear FLOAT,
#         visualbrowsertimespan TEXT,
#         nationality TEXT,
#         visualbrowsernationality TEXT,
#         constituenttype TEXT,
#         wikidataid TEXT,
#         PRIMARY KEY (constituentid),
#     );
    
#     CREATE OR REPLACE TABLE media (
#         mediaid	INTEGER,
#         mediatype TEXT,
#         title TEXT,
#         description TEXT,
#         duration FLOAT,
#         language TEXT,
#         thumbnailurl TEXT,
#         playurl TEXT,
#         downloadurl TEXT,
#         keywords TEXT,
#         tags TEXT,
#         imageurl TEXT,
#         presentationdate DATE,
#         releasedate DATE,
#         lastmodified DATE,
#         PRIMARY KEY (mediaid)
#     );
    
#     CREATE OR REPLACE TABLE media_relationships (
#         mediaid INTEGER,
#         relatedid INTEGER,
#         relatedentity TEXT,
#         PRIMARY KEY (mediaid, relatedid),
#         FOREIGN KEY (mediaid) REFERENCES media(mediaid),
#         FOREIGN KEY (relatedid) REFERENCES objects(objectid)
#     );
               
#     CREATE OR REPLACE TABLE text_entries (
#         objectid INTEGER,
#         text TEXT,
#         texttype TEXT,
#         year FLOAT,
#         FOREIGN KEY (objectid) REFERENCES objects(objectid),
#     );
    
#     CREATE OR REPLACE TABLE objects_cons (
#         objectid INTEGER,
#         constituentid INTEGER,
#         displayorder INTEGER,
#         roletype TEXT,
#         role TEXT,
#         prefix TEXT,
#         suffix TEXT,
#         displaydate TEXT,
#         beginyear FLOAT,
#         endyear FLOAT,
#         country TEXT,
#         zipcode TEXT,
#         PRIMARY KEY (objectid),
#         FOREIGN KEY (constituentid) REFERENCES cons(constituentid),
#     );
    
#     """)

In [19]:
con.sql("DROP TABLE IF EXISTS media_relationships")
con.sql("DROP TABLE IF EXISTS text_entries")
con.sql("DROP TABLE IF EXISTS objects_cons")
con.sql("DROP TABLE IF EXISTS objects")
con.sql("DROP TABLE IF EXISTS cons")
con.sql("DROP TABLE IF EXISTS media")

con.sql("""
CREATE OR REPLACE TABLE objects AS
SELECT * FROM objects_df
""")

con.sql("""
CREATE OR REPLACE TABLE cons AS
SELECT * FROM cons_df
""")

con.sql("""
CREATE OR REPLACE TABLE media AS
SELECT * FROM media_df
""")

con.sql("""
CREATE OR REPLACE TABLE media_relationships AS
SELECT * FROM media_relationships_df
""")

con.sql("""
CREATE OR REPLACE TABLE text_entries AS
SELECT * FROM text_entries_df
""")

con.sql("""
CREATE OR REPLACE TABLE objects_cons AS
SELECT * FROM objects_df
""")

In [20]:
sql_script = """
CREATE OR REPLACE TABLE objects AS
SELECT * FROM objects_df;

CREATE OR REPLACE TABLE cons AS
SELECT * FROM cons_df;

CREATE OR REPLACE TABLE media AS
SELECT * FROM media_df;

CREATE OR REPLACE TABLE media_relationships AS
SELECT * FROM media_relationships_df;

CREATE OR REPLACE TABLE text_entries AS
SELECT * FROM text_entries_df;

CREATE OR REPLACE TABLE objects_cons AS
SELECT * FROM objects_df;
"""

with open("museum_export.sql", "w") as f:
    f.write(sql_script)

In [21]:
con.sql("""SELECT * FROM media""")

┌───────────────┬───────────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬──────────┬──────────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────┬──────────────────────────────────────────────────────────────────────────────────────────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────┬────────────────────────┬────────────────────────┬────────────────────────┐
│    mediaid    │ mediatype │                                                           title                                                            │                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     description                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     │ duration │ language │                                                  thumbnailurl                                                  │                                                 playurl                                                 │                                          downloadurl                                           │                                         keywords                                         │                                                                          tags                                                                           │                                                   imageurl                                                    │    presentationdate    │      releasedate       │      lastmodified      │
│     int64     │  varchar  │                                                          varchar                                                           │                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       varchar                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       │  double  │ varchar  │                                                    varchar                                                     │                                                 varchar                                                 │                                            varchar                                             │                                         varchar                                          │                                                                         varchar                                                                         │                                                    varchar                                                    │        varchar         │        varchar         │        varchar         │
├───────────────┼───────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼──────────┼──────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────┼──────────────────────────────────────────────────────────────────────────────────────────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────┼────────────────────────┼────────────────────────┼────────────────────────┤
│           111 │ audio     │ John Wilmerding Symposium on American Art and Community Celebration 2021: Session I: An Evening Celebration of Alma Thomas │ <p>Virtual introduction by former First Lady Michelle Obama; poetry reading and discussion with Ross Gay; and virtual exhibition tour with Seth Feman and Jonathan Frederick Walz.<br>\r\n<br>\r\nRoss Gay, poet, gardener, professor, department of English, Indiana University Bloomington, founding board member, Bloomington Community Orchard, co-founder, The Tenderness Project, and Alma W. Thomas: Everything is Beautiful catalog contributor; with Seth Feman, deputy director for art and interpretation and curator of photography, Chrysler Museum of Art, and exhibition curator for Alma W. Thomas: Everything is Beautiful; and Jonathan Frederick Walz, director of curatorial affairs and curator of American art, Columbus Museum of Art, exhibition curator for Alma W. Thomas: Everything is Beautiful, and American University Feminist Art History Conference session presenter</p>\r\n                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     │     NULL │ en       │ https://www.nga.gov/content/dam/ngaweb/audio-video/video/thumbnails/wilmerding-2021-an-evening-celebration.jpg │ https://w.soundcloud.com/player/?url=https%3A%2F%2Fapi.soundcloud.com%2Ftracks%2F111&download=true      │ https://api.soundcloud.com/tracks/111/download?client_id=LBCcHmRB8XSStWL6wKH2HPACspQlXg2P      │ NULL                                                                                     │ ngaweb:constituents/1/9/2/6/Constituent_1926,ngaweb:audio-video/Symposia/wilmerding-symposium-on-american-art                                           │ https://www.nga.gov/content/dam/ngaweb/audio-video/video/infoboxes/wilmerding-2021-an-evening-celebration.jpg │ 2021-09-22 00:00:00-04 │ 2021-09-22 00:00:00-04 │ 2022-07-05 14:37:41-04 │
│      77997857 │ audio     │ National Gallery of Art String Quartet, Wind Quintet, and Piano Trio                                                       │ <p>Program: Music by Johann Sebastian Bach and Wolfgang Amadeus Mozart. National Gallery of Art resident ensembles play the music of Johann Sebastian Bach and Wolfgang Amadeus Mozart in a concert dedicated to the memory of Milton M. Gottesman. The string quartet performs Mozart's Quartet in C Major, K. 465 (&quot;Dissonant&quot;), the wind quintet plays Johann Sebastian Bach's Fugue in G Minor, BWV 593 (&quot;Little&quot;), and the piano trio presents two movements from Mozart's Piano Trio in B-flat Major, K. 502.</p>\n                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       │   3933.0 │ en       │ https://www.nga.gov/content/dam/ngaweb/audio-video/audio/thumbnails/nga-quartet.jpg                            │ https://w.soundcloud.com/player/?url=https%3A%2F%2Fapi.soundcloud.com%2Ftracks%2F77997857&download=true │ https://api.soundcloud.com/tracks/77997857/download?client_id=LBCcHmRB8XSStWL6wKH2HPACspQlXg2P │ string quartet, wind quintet, piano trio, johann sebastian bach, wolfgang amadeus mozart │ ngaweb:audio-video/audio,ngaweb:audio-video/music                                                                                                       │ https://www.nga.gov/content/dam/ngaweb/audio-video/audio/infoboxes/nga-quartet.jpg                            │ 2012-03-27 00:00:00-04 │ 2012-03-27 00:00:00-04 │ 2014-05-30 14:37:16-04 │
│      78008083 │ audio     │ National Gallery of Art New Music Ensemble                                                                                 │ <p>Program: Music by Steve Antosca and Judith Shatin. Music composed and arranged by Steve Antosca and Judith Shatin for performance in the West Building Rotunda on the occasion of the National Gallery of Art's 70th anniversary. Selections include the world premiere performances of Antosca's Echoic Landscape and Shatin's Sic transit, both composed in 2011, as well as Antosca's in every way I remember you, featuring saxophonist Noah Getz.</p>\n                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     │   2954.0 │ en       │ https://www.nga.gov/content/dam/ngaweb/audio-video/audio/thumbnails/nga-ensemble.jpg                           │ https://w.soundcloud.com/player/?url=https%3A%2F%2Fapi.soundcloud.com%2Ftracks%2F78008083&download=true │ https://api.soundcloud.com/tracks/78008083/download?client_id=LBCcHmRB8XSStWL6wKH2HPACspQlXg2P │ national, gallery, ensemble, shatin, antosca                                             │ ngaweb:audio-video/audio,ngaweb:audio-video/music                                                                                                       │ https://www.nga.gov/content/dam/ngaweb/audio-video/audio/infoboxes/nga-ensemble.jpg                           │ 2012-02-21 00:00:00-05 │ 2012-02-21 00:00:00-05 │ 2014-04-25 11:43:15-04 │

In [22]:
con.sql("EXPORT DATABASE 'museum_db_export'")

In [23]:
con.sql("DESCRIBE objects")

┌─────────────────────────────┬─────────────┬─────────┬─────────┬─────────┬─────────┐
│         column_name         │ column_type │  null   │   key   │ default │  extra  │
│           varchar           │   varchar   │ varchar │ varchar │ varchar │ varchar │
├─────────────────────────────┼─────────────┼─────────┼─────────┼─────────┼─────────┤
│ objectid                    │ BIGINT      │ YES     │ NULL    │ NULL    │ NULL    │
│ uuid                        │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ accessioned                 │ BIGINT      │ YES     │ NULL    │ NULL    │ NULL    │
│ accessionnum                │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ title                       │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ displaydate                 │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ beginyear                   │ DOUBLE      │ YES     │ NULL    │ NULL    │ NULL    │
│ endyear                     │ DOUBLE      │ YES     │ NULL    │ NULL    │ NULL    │
│ visualbrowsertimespan       │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ medium                      │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ dimensions                  │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ attributioninverted         │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ attribution                 │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ creditline                  │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ classification              │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ visualbrowserclassification │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ isvirtual                   │ BIGINT      │ YES     │ NULL    │ NULL    │ NULL    │
│ departmentabbr              │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ lastdetectedmodification    │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ wikidataid                  │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
└─────────────────────────────┴─────────────┴─────────┴─────────┴─────────┴─────────┘
  20 rows                                                                 6 columns

## Creating Database

Does the National Art Museum use data management and storage techniques that allow for the preservation and accessibility of digital objects?

In [31]:
digital_objects = con.sql("SELECT * FROM media").df()

In [ ]:
import requests

def check_url(url):
    try:
        response = requests.get(url, timeout=5)
        return response.status_code
    except requests.exceptions.RequestException:
        return None
    
digital_objects['status_code'] = digital_objects['playurl'].apply(check_url)
digital_objects['404_error'] = digital_objects['status_code'] == 404
digital_objects

,mediaid,mediatype,title,description,duration,language,thumbnailurl,playurl,downloadurl,keywords,tags,imageurl,presentationdate,releasedate,lastmodified,status_code,404_error
0,111,audio,John Wilmerding Symposium on American Art and ...,<p>Virtual introduction by former First Lady M...,NaN,en,https://www.nga.gov/content/dam/ngaweb/audio-v...,https://w.soundcloud.com/player/?url=https%3A%...,https://api.soundcloud.com/tracks/111/download...,None,"ngaweb:constituents/1/9/2/6/Constituent_1926,n...",https://www.nga.gov/content/dam/ngaweb/audio-v...,2021-09-22 00:00:00-04,2021-09-22 00:00:00-04,2022-07-05 14:37:41-04,404,True
1,77997857,audio,"National Gallery of Art String Quartet, Wind Q...",<p>Program: Music by Johann Sebastian Bach and...,3933.0,en,https://www.nga.gov/content/dam/ngaweb/audio-v...,https://w.soundcloud.com/player/?url=https%3A%...,https://api.soundcloud.com/tracks/77997857/dow...,"string quartet, wind quintet, piano trio, joha...","ngaweb:audio-video/audio,ngaweb:audio-video/music",https://www.nga.gov/content/dam/ngaweb/audio-v...,2012-03-27 00:00:00-04,2012-03-27 00:00:00-04,2014-05-30 14:37:16-04,200,False
2,78008083,audio,National Gallery of Art New Music Ensemble,<p>Program: Music by Steve Antosca and Judith ...,2954.0,en,https://www.nga.gov/content/dam/ngaweb/audio-v...,https://w.soundcloud.com/player/?url=https%3A%...,https://api.soundcloud.com/tracks/78008083/dow...,"national, gallery, ensemble, shatin, antosca","ngaweb:audio-video/audio,ngaweb:audio-video/music",https://www.nga.gov/content/dam/ngaweb/audio-v...,2012-02-21 00:00:00-05,2012-02-21 00:00:00-05,2014-04-25 11:43:15-04,200,False
3,78016915,audio,Nordic Voices,<p>Program: Norwegian vocal music. Nordic Voic...,2368.0,en,https://www.nga.gov/content/dam/ngaweb/audio-v...,https://w.soundcloud.com/player/?url=https%3A%...,https://api.soundcloud.com/tracks/78016915/dow...,"nordic, voices, norway, vocal, acapella","ngaweb:audio-video/audio,ngaweb:audio-video/music",https://www.nga.gov/content/dam/ngaweb/audio-v...,2010-10-10 00:00:00-04,2012-01-17 00:00:00-05,2014-04-25 11:43:40-04,200,False
4,78025867,audio,Music to Honor the Chester Dale Collection,"<p>Program: Music by Gershwin, Milhaud, Porter...",3285.0,en,https://www.nga.gov/content/dam/ngaweb/audio-v...,https://w.soundcloud.com/player/?url=https%3A%...,https://api.soundcloud.com/tracks/78025867/dow...,"dale, chester, gershwin, milhaud, porter, stra...","ngaweb:audio-video/audio,ngaweb:audio-video/mu...",https://www.nga.gov/content/dam/ngaweb/audio-v...,2011-12-13 00:00:00-05,2011-12-13 00:00:00-05,2014-05-16 13:37:10-04,200,False

In [37]:
import requests
from concurrent.futures import ThreadPoolExecutor

def visit_website(url):
    try:
        response = requests.head(url, timeout=5, allow_redirects=True)
        return response.status_code
    except Exception:
        return "Error"

with ThreadPoolExecutor(max_workers=20) as executor:
    digital_objects['play_url_status_code'] = list(executor.map(visit_website, digital_objects['playurl']))

with ThreadPoolExecutor(max_workers=20) as executor:
    digital_objects['thumbnailurl_status_code'] = list(executor.map(visit_website, digital_objects['thumbnailurl']))

with ThreadPoolExecutor(max_workers=20) as executor:
    digital_objects['downloadurl_status_code'] = list(executor.map(visit_website, digital_objects['downloadurl']))

with ThreadPoolExecutor(max_workers=20) as executor:
    digital_objects['imageurl_status_code'] = list(executor.map(visit_website, digital_objects['imageurl']))

In [38]:
digital_objects

,mediaid,mediatype,title,description,duration,language,thumbnailurl,playurl,downloadurl,keywords,tags,imageurl,presentationdate,releasedate,lastmodified,status_code,play_url_status_code,thumbnailurl_status_code,downloadurl_status_code,imageurl_status_code
0,111,audio,John Wilmerding Symposium on American Art and ...,<p>Virtual introduction by former First Lady M...,NaN,en,https://www.nga.gov/content/dam/ngaweb/audio-v...,https://w.soundcloud.com/player/?url=https%3A%...,https://api.soundcloud.com/tracks/111/download...,None,"ngaweb:constituents/1/9/2/6/Constituent_1926,n...",https://www.nga.gov/content/dam/ngaweb/audio-v...,2021-09-22 00:00:00-04,2021-09-22 00:00:00-04,2022-07-05 14:37:41-04,404,404,404,401,404
1,77997857,audio,"National Gallery of Art String Quartet, Wind Q...",<p>Program: Music by Johann Sebastian Bach and...,3933.0,en,https://www.nga.gov/content/dam/ngaweb/audio-v...,https://w.soundcloud.com/player/?url=https%3A%...,https://api.soundcloud.com/tracks/77997857/dow...,"string quartet, wind quintet, piano trio, joha...","ngaweb:audio-video/audio,ngaweb:audio-video/music",https://www.nga.gov/content/dam/ngaweb/audio-v...,2012-03-27 00:00:00-04,2012-03-27 00:00:00-04,2014-05-30 14:37:16-04,200,200,404,401,404
2,78008083,audio,National Gallery of Art New Music Ensemble,<p>Program: Music by Steve Antosca and Judith ...,2954.0,en,https://www.nga.gov/content/dam/ngaweb/audio-v...,https://w.soundcloud.com/player/?url=https%3A%...,https://api.soundcloud.com/tracks/78008083/dow...,"national, gallery, ensemble, shatin, antosca","ngaweb:audio-video/audio,ngaweb:audio-video/music",https://www.nga.gov/content/dam/ngaweb/audio-v...,2012-02-21 00:00:00-05,2012-02-21 00:00:00-05,2014-04-25 11:43:15-04,200,200,404,401,404
3,78016915,audio,Nordic Voices,<p>Program: Norwegian vocal music. Nordic Voic...,2368.0,en,https://www.nga.gov/content/dam/ngaweb/audio-v...,https://w.soundcloud.com/player/?url=https%3A%...,https://api.soundcloud.com/tracks/78016915/dow...,"nordic, voices, norway, vocal, acapella","ngaweb:audio-video/audio,ngaweb:audio-video/music",https://www.nga.gov/content/dam/ngaweb/audio-v...,2010-10-10 00:00:00-04,2012-01-17 00:00:00-05,2014-04-25 11:43:40-04,200,200,404,429,404
4,78025867,audio,Music to Honor the Chester Dale Collection,"<p>Program: Music by Gershwin, Milhaud, Porter...",3285.0,en,https://www.nga.gov/content/dam/ngaweb/audio-v...,https://w.soundcloud.com/player/?url=https%3A%...,https://api.soundcloud.com/tracks/78025867/dow...,"dale, chester, gershwin, milhaud, porter, stra...","ngaweb:audio-video/audio,ngaweb:audio-video/mu...",https://www.nga.gov/content/dam/ngaweb/audio-v...,2011-12-13 00:00:00-05,2011-12-13 00:00:00-05,2014-05-16 13:37:10-04,200,200,404,401,404
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2680,6338395687112,video,"The Circle Lecture, Molly Donovan, The Land Ca...","<p><span style=""font-style: normal; font-varia...",NaN,en,https://www.nga.gov/content/dam/ngaweb/audio-v...,https://players.brightcove.net/1191289016001/d...,None,None,ngaweb:audio-video/development,https://www.nga.gov/content/dam/ngaweb/audio-v...,2023-09-29 00:00:00-04,2023-09-29 00:00:00-04,2023-10-06 11:20:52-04,200,200,404,Error,404
2681,6339481510112,video,"The Circle Lecture, Sarah Greenough, Etched by...","<p><span style=""font-style: normal; font-varia...",NaN,en,https://www.nga.gov/content/dam/ngaweb/audio-v...,https://players.brightcove.net/1191289016001/d...,None,None,ngaweb:audio-video/development,https://www.nga.gov/content/dam/ngaweb/audio-v...,2023-10-18 00:00:00-04,2023-10-18 00:00:00-04,2023-10-20 09:31:11-04,200,200,404,Error,404
2682,6341066711112,video,"The Circle Lecture, Philip Brookman, Dorothea ...","<p><span style=""font-style: normal; font-varia...",NaN,en,https://www.nga.gov/content/dam/ngaweb/audio-v...,https://players.brightcove.net/1191289016001/d...,None,None,ngaweb:audio-video/development,https://www.nga.gov/content/dam/ngaweb/audio-v...,2023-11-09 00:00:00-05,2023-11-09 00:00:00-05,2023-11-14 11:50:45-05,200,200,404,Error,404
2683,6342474760112,video,Mark Rothko: A Conversation with Arne Glimcher...,<p>Join us for a conversation about Mark Rothk...,NaN,en,https://www.nga.gov/content/dam/ngaweb/audio-v...,https://players.brightcove.net/1191289016001/d...,None,None,ngaweb:audio-video/development,https://www.nga.gov/content/dam/ngaweb/audio-v...,2023-11-17 00:00:00-05,2023-11-17 00:00:00-05,2024-01-02 08:37:17-05,200,200,404,Error,404
2684,6347331959112,video,"The Circle Lecture, Shelley Langdale, The Anxi...","<p>Shelley R. Langdale, Curator and Head of Mo...",NaN,en,https://www.nga.gov/content/dam/ngaweb/audio-v...,https://players.brightcove.net/1191289016001/d...,None,None,ngaweb:audio-video/development,https://www.nga.gov/content/dam/ngaweb/audio-v...,2024-02-09 00:00:00-05,2024-02-09 00:00:00-05,2024-02-21 14:45:58-05,200,200,404,Error,404

What is the difference between how digital and traditional media in the National Art Museum is treated? Are there more digital items or traditional items?

We want to know what the relationship is between older, traditional works of art and modern works at the National Art Museum in terms of what region they come from and the artist who made them.