In [1]:
import pandas as pd

constituents_url = 'https://raw.githubusercontent.com/NationalGalleryOfArt/opendata/08bc72ca5fccf86ca4f3702f9db068a11a592509/data/constituents.csv'
cons_df = pd.read_csv(constituents_url)
objects_url = 'https://raw.githubusercontent.com/NationalGalleryOfArt/opendata/refs/heads/main/data/objects.csv'
objects_df = pd.read_csv(objects_url)
objects_constituents_url = 'https://raw.githubusercontent.com/NationalGalleryOfArt/opendata/refs/heads/main/data/objects_constituents.csv'
objects_cons_df = pd.read_csv(objects_constituents_url)
text_entries_url = 'https://raw.githubusercontent.com/NationalGalleryOfArt/opendata/refs/heads/main/data/objects_text_entries.csv'
text_entries_df = pd.read_csv(text_entries_url)
media_items_url = 'https://raw.githubusercontent.com/NationalGalleryOfArt/opendata/refs/heads/main/data/media_items.csv'
media_df = pd.read_csv(media_items_url)
media_relationships_url = 'https://raw.githubusercontent.com/NationalGalleryOfArt/opendata/refs/heads/main/data/media_relationships.csv'
media_relationships_df = pd.read_csv(media_relationships_url)

/var/folders/w7/23_x_krd56dgz3l_g0tp_m0w0000gn/T/ipykernel_51147/689904132.py:6: DtypeWarning: Columns (24) have mixed types. Specify dtype option on import or set low_memory=False.
  objects_df = pd.read_csv(objects_url)
/var/folders/w7/23_x_krd56dgz3l_g0tp_m0w0000gn/T/ipykernel_51147/689904132.py:8: DtypeWarning: Columns (11) have mixed types. Specify dtype option on import or set low_memory=False.
  objects_cons_df = pd.read_csv(objects_constituents_url)

## Data Cleaning

In [2]:
media_relationships_df.dtypes
media_relationships_df.isna().sum()

mediaid          0
relatedid        0
relatedentity    0
dtype: int64

In [3]:
media_df.isna().sum()
media_df.dtypes

mediaid               int64
mediatype            object
title                object
description          object
duration            float64
language             object
thumbnailurl         object
playurl              object
downloadurl          object
keywords             object
tags                 object
imageurl             object
presentationdate     object
releasedate          object
lastmodified         object
dtype: object

In [4]:
objects_df.isna().sum()

objectid                            0
uuid                                0
accessioned                         0
accessionnum                        0
locationid                     141720
title                               0
displaydate                     11524
beginyear                          50
endyear                            68
visualbrowsertimespan              50
medium                           1241
dimensions                      21017
inscription                     60826
markings                       129078
attributioninverted                 0
attribution                         0
provenancetext                  64958
creditline                         25
classification                      0
subclassification              101617
visualbrowserclassification         0
parentid                       114107
isvirtual                           0
departmentabbr                      0
portfolio                      141379
series                         105364
volume                         141818
watermarks                     134252
lastdetectedmodification            0
wikidataid                      16580
customprinturl                 143701
dtype: int64

In [6]:
limit = len(objects_df) * 0.7
objects_df = objects_df.dropna(thresh=limit, axis=1)

In [7]:
target_cols = ['medium', 'dimensions', 'inscription', 'markings', 'provenancetext']

available_cols = [col for col in target_cols if col in objects_df.columns]

objects_df[available_cols] = objects_df[available_cols].fillna("Unknown")

/var/folders/w7/23_x_krd56dgz3l_g0tp_m0w0000gn/T/ipykernel_51147/1025383810.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  objects_df[available_cols] = objects_df[available_cols].fillna("Unknown")

In [8]:
print(objects_df.columns.tolist())

['objectid', 'uuid', 'accessioned', 'accessionnum', 'title', 'displaydate', 'beginyear', 'endyear', 'visualbrowsertimespan', 'medium', 'dimensions', 'attributioninverted', 'attribution', 'creditline', 'classification', 'visualbrowserclassification', 'isvirtual', 'departmentabbr', 'lastdetectedmodification', 'wikidataid']

In [9]:
objects_df = objects_df.dropna(subset=['beginyear', 'endyear', 'creditline', 'visualbrowsertimespan'])

In [10]:
objects_df.isna().sum()

objectid                           0
uuid                               0
accessioned                        0
accessionnum                       0
title                              0
displaydate                    11472
beginyear                          0
endyear                            0
visualbrowsertimespan              0
medium                             0
dimensions                         0
attributioninverted                0
attribution                        0
creditline                         0
classification                     0
visualbrowserclassification        0
isvirtual                          0
departmentabbr                     0
lastdetectedmodification           0
wikidataid                     16512
dtype: int64

In [11]:
if 'displaydate' in objects_df.columns:
    objects_df['displaydate'] = objects_df['displaydate'].fillna(objects_df['beginyear'].astype(str))
    
if 'wikidataid' in objects_df.columns:
    objects_df['wikidataid'] = objects_df['wikidataid'].fillna('Not Linked')

In [12]:
objects_df.isna().sum()

objectid                       0
uuid                           0
accessioned                    0
accessionnum                   0
title                          0
displaydate                    0
beginyear                      0
endyear                        0
visualbrowsertimespan          0
medium                         0
dimensions                     0
attributioninverted            0
attribution                    0
creditline                     0
classification                 0
visualbrowserclassification    0
isvirtual                      0
departmentabbr                 0
lastdetectedmodification       0
wikidataid                     0
dtype: int64

In [13]:
objects_cons_df.dtypes
objects_cons_df.isna().sum()
#objects_cons_df.roletype.unique()
#objects_cons_df
objects_cons_df['objectid'] = objects_cons_df['objectid'].replace(0, 'NaN')

In [14]:
objects_df.isna().sum()

objectid                       0
uuid                           0
accessioned                    0
accessionnum                   0
title                          0
displaydate                    0
beginyear                      0
endyear                        0
visualbrowsertimespan          0
medium                         0
dimensions                     0
attributioninverted            0
attribution                    0
creditline                     0
classification                 0
visualbrowserclassification    0
isvirtual                      0
departmentabbr                 0
lastdetectedmodification       0
wikidataid                     0
dtype: int64

Constituents, objects_constituents down

In [15]:
objects_cons_df.dtypes
objects_cons_df.isna().sum()
objects_cons_df

,objectid,constituentid,displayorder,roletype,role,prefix,suffix,displaydate,beginyear,endyear,country,zipcode
0,NaN,12,4,owner,current owner,NaN,NaN,1937 -,1937.0,NaN,United States,20565.0
1,NaN,427,1,donor,donor,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,427,2,donor,source,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,427,3,owner,previous owner,NaN,NaN,1936 - 1937,1936.0,1937.0,NaN,NaN
4,NaN,1102,1,owner,previous owner,NaN,", New York, NY",- 1936,NaN,1936.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
839057,233967,12,2,owner,current owner,NaN,NaN,NaN,NaN,NaN,NaN,NaN
839058,233967,27654,1,donor,source,NaN,NaN,NaN,NaN,NaN,NaN,NaN
839059,233967,27654,1,owner,previous owner,NaN,NaN,NaN,NaN,NaN,NaN,NaN
839060,233967,27654,2,donor,donor,NaN,NaN,NaN,NaN,NaN,NaN,NaN
839061,233967,44363,1,artist,artist,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
cons_df.dtypes
cons_df.isna().sum()
cons_df
remove = ['anonymous artist', 'anonymous']
cons_df['preferreddisplayname'] = cons_df['preferreddisplayname'].str.lower().str.strip()
cons_df['preferreddisplayname'] = cons_df['preferreddisplayname'].replace(remove, 'Anonymous')
cons_df
cons_df['forwarddisplayname'] = cons_df['forwarddisplayname'].str.lower().str.strip()
cons_df['forwarddisplayname'] = cons_df['forwarddisplayname'].replace(remove, 'Anonymous')
cons_df

,constituentid,uuid,ulanid,preferreddisplayname,forwarddisplayname,lastname,displaydate,artistofngaobject,beginyear,endyear,visualbrowsertimespan,nationality,visualbrowsernationality,constituenttype,wikidataid
0,9,57edbe2d-6702-4d41-9190-2a2945bc2c89,NaN,Anonymous,Anonymous,NaN,Anonymous,0,NaN,NaN,NaN,NaN,Other,anonymous,NaN
1,11,125c640d-e39b-4ae4-8455-f0b5e913c09e,NaN,"baldung, hans",hans baldung,Baldung,NaN,1,NaN,NaN,NaN,NaN,Other,individual,NaN
2,12,e4d45117-9800-4315-9184-916c53e64c8d,500115983.0,national gallery of art,national gallery of art,NaN,NaN,0,NaN,NaN,NaN,NaN,Other,corporate,Q214867
3,13,7331a3f2-50fd-4838-b41d-f8013eb2456c,NaN,Anonymous,Anonymous,Anonymous Artist,NaN,1,NaN,NaN,NaN,Unknown,Other,anonymous,Q4233718
4,14,6b4e3681-b09e-4cbd-9f3c-ff7830173c59,NaN,"evans, thomas m., mrs.",mrs. thomas m. evans,Evans,"American, 1923 - 2013",0,1923.0,2013.0,1901 to 1925,American,American,individual,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27766,54663,7e507508-19be-46a5-ac77-dceb689fc6b4,NaN,alex cooper auctioneers,alex cooper auctioneers,NaN,founded 1924,0,1924.0,NaN,1901 to 1925,NaN,Other,corporate,NaN
27767,54692,cc016903-caeb-473c-821a-b27d5b254b8b,NaN,"prager, joanne",joanne prager,Prager,NaN,0,NaN,NaN,NaN,NaN,Other,individual,NaN
27768,54706,126a49b4-5184-4a31-864f-ae62f425b5c6,NaN,craven allen gallery,craven allen gallery,NaN,NaN,0,NaN,NaN,NaN,NaN,Other,corporate,NaN
27769,54719,70c9d72b-9e65-4796-8090-4eb59da84357,NaN,"bullock, raymond",raymond bullock,Bullock,American,0,NaN,NaN,NaN,American,American,individual,NaN
27770,54759,42d329a1-81c5-427e-84ff-21bafca600a9,NaN,"odieuvre, michel",michel odieuvre,Odieuvre,"French, 1687 - 1756",1,1687.0,1756.0,1651 to 1700,French,French,individual,NaN

## Creating Database

In [17]:
import duckdb
import pandas as pd
import os

con = duckdb.connect("Museum.db")
print("Connected to Museum.db")

Connected to Museum.db

In [25]:
objects_df

,objectid,uuid,accessioned,accessionnum,title,displaydate,beginyear,endyear,visualbrowsertimespan,medium,dimensions,attributioninverted,attribution,creditline,classification,visualbrowserclassification,isvirtual,departmentabbr,lastdetectedmodification,wikidataid
0,0,b5dc500c-be86-4b05-93fa-59a25d8775fb,1,1937.1.2.c,Saint James Major,c. 1310,1310.0,1310.0,1300 to 1400,tempera on panel,painted surface (top of gilding): 62.2 × 34.8 ...,Grifo di Tancredi,Grifo di Tancredi,Andrew W. Mellon Collection,Painting,painting,0,CIS-R,2023-05-09 17:01:03.48-04,Q20172973
1,1,59e0e07c-208e-4d24-a3d3-f4a56d20d6d3,1,1937.1.3,Saint Paul and a Group of Worshippers,1333,1333.0,1333.0,1300 to 1400,tempera on panel,painted surface: 224.8 × 77 cm (88 1/2 × 30 5/...,"Daddi, Bernardo",Bernardo Daddi,Andrew W. Mellon Collection,Painting,painting,0,CIS-R,2024-02-12 16:33:23.167-05,Q20173083
2,2,95cfbfd3-5947-4834-b1cf-bf92ee1a7340,1,1937.1.4.a,Saint Andrew and Saint Benedict with the Archa...,shortly before 1387,1387.0,1387.0,1300 to 1400,tempera on poplar panel,overall: 197 × 80 cm (77 9/16 × 31 1/2 in.),"Gaddi, Agnolo",Agnolo Gaddi,Andrew W. Mellon Collection,Painting,painting,0,CIS-R,2024-03-08 14:32:09.57-05,Q20173290
3,3,3277a6d0-d92e-4684-9d86-2be2cbe3c5f2,1,1937.1.4.b,Madonna and Child Enthroned with Twelve Angels...,shortly before 1387,1387.0,1387.0,1300 to 1400,tempera on poplar panel,overall: 204 × 80 cm (80 5/16 × 31 1/2 in.),"Gaddi, Agnolo",Agnolo Gaddi,Andrew W. Mellon Collection,Painting,painting,0,CIS-R,2024-03-08 14:32:09.57-05,Q20173280
4,4,63225dec-d421-4ece-9f2a-335dd2dfeea1,1,1937.1.4.c,Saint Bernard and Saint Catherine of Alexandri...,shortly before 1387,1387.0,1387.0,1300 to 1400,tempera on poplar panel,overall: 194.6 × 80 cm (76 5/8 × 31 1/2 in.),"Gaddi, Agnolo",Agnolo Gaddi,Andrew W. Mellon Collection,Painting,painting,0,CIS-R,2024-03-08 14:32:09.57-05,Q20173299
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144187,232396,85d83d4b-477b-4f99-89a4-bc184fdf4d37,1,2025.100.141,Portrait of a Man,c. 1931,1926.0,1936.0,1926 to 1950,gelatin silver print,image: 19.2 × 14.4 cm (7 9/16 × 5 11/16 in.)\r...,"Wolff, Paul, Dr.",Dr. Paul Wolff,"Gift of Manfred Heiting, Los Angeles",Photograph,photograph,0,CPH,2026-02-13 22:01:41.52-05,Not Linked
144188,232405,40b10576-6067-4cd8-bc4f-f524deda4128,1,2025.93.1,Hagar I,1948,1948.0,1948.0,1926 to 1950,bronze,overall: 81.28 × 88.9 × 40.64 cm (32 × 35 × 16...,"Lipchitz, Jacques",Jacques Lipchitz,Gift (Partial and Promised) of Steve and Neysa...,Sculpture,sculpture,0,CMC,2026-02-27 22:01:38.93-05,Not Linked
144189,232408,01e3a928-f505-405e-888f-9f8949f5098a,1,2025.92.1,Tabula,1973,1973.0,1973.0,1951 to 1975,acrylic on canvas,overall: 230 × 196 cm (90 9/16 × 77 3/16 in.),"Hantaï, Simon",Simon Hantaï,Gift of Martin and Toni Sosnoff,Painting,painting,0,CMC,2026-02-09 20:22:24.733-05,Not Linked
144190,233932,01e21be8-2ef9-4f30-9580-e6b99b867327,1,2025.101.2.1-50,Genesis,2005,2005.0,2005.0,2001 to present,portfolio of 50 platinum prints,overall: 71.12 × 88.9 × 8.26 cm (28 × 35 × 3 1...,"Salgado, Sebastião",Sebastião Salgado,Gift of Marsha Garces Williams,Portfolio,portfolio,0,CPH,2026-02-20 22:01:39.217-05,Not Linked
144191,233967,29ceab01-0cc3-4df8-81df-8eaa02478695,1,2025.98.1-69,The Family,"May 5, 1976",1976.0,1976.0,1976 to 2000,69 gelatin silver prints and original 1976 Rol...,image (visible; each): 25.1 × 20.3 cm (9 7/8 ×...,"Avedon, Richard",Richard Avedon,Gift of John Pritzker,Portfolio,portfolio,0,CPH,2026-03-04 22:01:40.283-05,Not Linked

In [27]:
objects_cons_df

,objectid,constituentid,displayorder,roletype,role,prefix,suffix,displaydate,beginyear,endyear,country,zipcode
0,NaN,12,4,owner,current owner,NaN,NaN,1937 -,1937.0,NaN,United States,20565.0
1,NaN,427,1,donor,donor,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,427,2,donor,source,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,427,3,owner,previous owner,NaN,NaN,1936 - 1937,1936.0,1937.0,NaN,NaN
4,NaN,1102,1,owner,previous owner,NaN,", New York, NY",- 1936,NaN,1936.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
839057,233967,12,2,owner,current owner,NaN,NaN,NaN,NaN,NaN,NaN,NaN
839058,233967,27654,1,donor,source,NaN,NaN,NaN,NaN,NaN,NaN,NaN
839059,233967,27654,1,owner,previous owner,NaN,NaN,NaN,NaN,NaN,NaN,NaN
839060,233967,27654,2,donor,donor,NaN,NaN,NaN,NaN,NaN,NaN,NaN
839061,233967,44363,1,artist,artist,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
with open("museum.sql", "w") as file:
    file.write("""
    
     CREATE OR REPLACE TABLE objects (
        PRIMARY KEY (objectid),
        objectid INTEGER,
        uuid TEXT,
        accessioned INTEGER,
        accessionnum TEXT,
        title TEXT,
        displaydate DATE,
        beginyear FLOAT,
        endyear FLOAT,
        visualbrowsertimespan TEXT,
        medium TEXT,
        dimensions TEXT,
        attributioninverted TEXT,
        attribution TEXT,
        creditline TEXT,
        isvirtual INTEGER,
        departmntabbr TEXT,
        lastdetectmodification TEXT,
        wikidataid TEXT,
        merged_classification TEXT,
        );
               
    CREATE OR REPLACE TABLE cons (
        constituentid INTEGER,
        uuid object,
        ulanid FLOAT,
        preferreddisplayname TEXT,
        forwarddisplayname TEXT,
        lastname TEXT,
        displaydate TEXT,
        artistofngaobject INT,
        beginyear FLOAT,
        endyear FLOAT,
        visualbrowsertimespan TEXT,
        nationality TEXT,
        visualbrowsernationality TEXT,
        constituenttype TEXT,
        wikidataid TEXT,
        PRIMARY KEY (constituentid INT),
    );
    
    CREATE OR REPLACE TABLE media (
        mediaid	INTEGER,
        mediatype TEXT,
        title TEXT,
        description TEXT,
        duration FLOAT,
        language TEXT,
        thumbnailurl TEXT,
        playurl TEXT,
        downloadurl TEXT,
        keywords TEXT,
        tags TEXT,
        imageurl TEXT,
        presentationdate DATE,
        releasedate DATE,
        lastmodified DATE,
        PRIMARY KEY (mediaid)
    );
    
    CREATE OR REPLACE TABLE media_relationships (
        mediaid INTEGER,
        relatedid INTEGER,
        relatedentity TEXT,
        PRIMARY KEY (mediaid, relatedid),
        FOREIGN KEY (mediaid) REFERENCES media(mediaid),
        FOREIGN KEY (relatedid) REFERENCES objects(objectid)
    );
               
    CREATE OR REPLACE TABLE text_entries (
        objectid INTEGER,
        text TEXT,
        texttype TEXT,
        year FLOAT,
        FOREIGN KEY (objectid) REFERENCES objects(objectid),
    );
    
    CREATE OR REPLACE TABLE objects_cons (
        objectid INTEGER,
        constituentid INTEGER,
        displayorder INTEGER,
        roletype TEXT,
        role TEXT,
        prefix TEXT,
        suffix TEXT,
        displaydate TEXT,
        beginyear FLOAT,
        endyear FLOAT,
        country TEXT,
        zipcode TEXT,
        PRIMARY KEY (objectid),
        FOREIGN KEY (constituentid) REFERENCES cons(constituentid),
    );
    
    """)